POST http://localhost:3000/expenses/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTg1ZTA0OS03OWE2LTQ2OGUtYjBiYy0zYTMwZWE3OTRjN2YiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzMyMDQwMDc4LCJleHAiOjE3MzIwNDM2Nzh9.6rq-Z7Gq8Yppv2WcN5CGGdihYgUXphUWh6FXXvS_yAY

{
  "description": "Expense 1",
  "amount": 100,
  "date": "2018-05-01",
  "category": "Groceries"
}
